name: PKU-auto-epidemic-fighter

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
  watch:
    types: started
env:
  SCKEY: ${{ secrets.SCKEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: install requests
        run: pip install requests
      - name: GOGOGO
        run: python main.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} -f ${{ secrets.FORM }}
